name: 'ci'

on:
  push:
    branches:
      - main

jobs:
  golangci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.17.x]
    name: lint & test
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: testing
        run: go test -v ./...
